name: TESTING
on: [push]
jobs:
  build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.6, 3.7, 3.8]
        steps:
            - uses: actions/checkout@v2
            - name: python install
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
                architecture: x64
            - name: RunTest
              run: python -m unittest discover .
