name: Python Package

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python all python versions
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
